# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353e664698b7b7a56304e4d9c2cb87e411b0648fa38b14b79038664388c5b1ebf2015c44f9c0dc5869ca68148baba86740da766934df9645c15e30250001fe6f

test:
  secret_key_base: 1b9b765e6e0a23f1dfa184265b7532aa35b92b5db46063475211685729a73956a9b4f22958d9ba88218666c09777e0e89cae850bbef39d487468025f47fa8890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
